
# Used for parallelization by snakemake. This setting is based on the architecture of the metal-as-as-service 
# node netdc-bms-c11g.maas - which has 56 cores. Adjust this setting as needed. For example, on most laptops
# a reasonable value might be 4, or 8.
cpu_cores: 4

# Number of outgroups to include in each family-level analysis. Minimum is 2.
outgroups: 3

# Used for verbosity, see `logging` from stdlib
log_level: 'INFO'

# Either use COI-5P or matK_rbcL
marker: COI-5P

# Substitution model in RAxML CLI syntax
model: GTR+G

# Minimum length to include (this fits COI-5P)
minlength: 600

# Minimum number of sequences per alignment
minseq: 3

# Which exemplars to pick: tallest, shortest, or median
exemplars: tallest

# How to rescale the subtrees: exemplars (i.e. subtree depth ratio) or outgroup (crown-to-crown distance ratio)
scaling: exemplars

# Maximum number of sequences per alignment
maxseq: 12000

# Nucleotide alignments (NT) or aminoacid (AA) for MACSE alignment
datatype: NT

# Choose which records to use from the database for the pipeline. filter_name only takes one name, so does filter level.
# filter levels: class, order, family, genus, all (no filter)
fasta_filter:
  # max level: family
  filter_level: kingdom
  filter_name: Animalia
  # Maximum number of sequences per fasta
  # if above, fasta files are generated not at the family level but at lower rank i.e., genus or, if still
  # too many sequences, at species level
  max_fasta_seq: 200

name: phylogeny

blastdb: blastdb

dependencies:
  - pip:
      - -r requirements.txt

file_names:
  bold_tsv: resources/BOLD_Public.21-Jun-2024.curated.NL.tsv
  open_tre: resources/opentree/opentree14.9_tree/labelled_supertree/labelled_supertree.tre
  hmm: resources/hmm/COI-5P.hmm
  fasta_dir: results/fasta/
  blast_dir: results/blast

