
configfile: "config.yaml"

database_file = "../data/databases/BOLD_{}_barcodes.db".format(config["marker"])
datatype = config['datatype']
ott_database_file = "../data/databases/outfile.db"


rule unzip:
    input: config["file_names"]["bold_zip"]
    output: config["file_names"]["bold_tsv"]
    threads: config["cpu_cores"]
    script:
        "unzip_targz.py"


rule create_database:
  input: config["file_names"]["bold_tsv"]
  output: 'temporary_database.db'
  params:
    marker=config["marker"],
    minlength=config["minlength"],
    log_level=config['log_level']
  threads: config["cpu_cores"]
  script:
      "bold_data_dump.py"


rule map_opentol:
  input: 'temporary_database.db'
  output: database_file
  params:
    marker=config['marker'],
    log_level=config['log_level']
  threads: config["cpu_cores"]
  script:
      "map_opentol.py"


rule family_fasta:
    input:
        database_file
    output:
        dynamic("../data/fasta/family/{family}.fasta")
    params:
        log_level=config['log_level'],
        fasta_dir=config['file_names']['fasta_dir'],
        filter_level=config['fasta_filter']['filter_level'],
        filter_name=config['fasta_filter']['filter_name'],
        maxseq=config['maxseq'],
        minseq=config['minseq']
    threads:
        config["cpu_cores"]
    script:
        "family_fasta.py"

rule hmm_build:
    #input:
    output:
        sequence_file = "../data/fasta/family/hmm/seq_all_{}.fasta".format(config["marker"]),
        alignment_file = "../data/fasta/family/hmm/seq_aln_{}.fasta".format(config["marker"])
    params:
        log_level=config['log_level'],
        hmm=config['file_names']['hmm']
    threads:
        config["cpu_cores"]
    script:
        "hmm_build.py"


rule hmm_align:
    input:  "../data/fasta/family/{family}.fasta"
    output: "../data/fasta/alignment/{{family}}_{}_hmm.fasta".format(datatype)
    params:
        log_level=config['log_level'],
        hmm=config['file_names']['hmm']
    threads:
        config["cpu_cores"]
    script:
        "msa_hmm.py"


rule get_opentree_zip:
    output: "../data/opentree/opentree13.4_tree/labelled_supertree/labelled_supertree.tre"
    threads: config["cpu_cores"]
    shell:  "wget -P ../data/opentree/ https://files.opentreeoflife.org/synthesis/opentree13.4/opentree13.4tree.tgz && tar -xvzf ../data/opentree/opentree13.4tree.tgz --directory ../data/opentree"


rule unique_otts:
    input: "../data/fasta/alignment/{{family}}_{}_hmm.fasta".format(datatype)
    output: "../data/ott_lists/{family}_otts.txt"
    threads: config["cpu_cores"]/2
    shell: "cat {input} | egrep '>' | cut -f1 -d  '|' | cut -c 2- | sort -u > {output}"


rule megatree_loader:
    input: "../data/opentree/opentree13.4_tree/labelled_supertree/labelled_supertree.tre"
    output: "../data/databases/opentree_nodes.db"
    threads: config["cpu_cores"]
    shell: "megatree-loader -i {input} -d {output}"


rule megatree_pruner:
    input: "../data/databases/opentree_nodes.db", "../data/ott_lists/{family}_otts.txt"
    output: "../data/newick/{family}_constraint_temp.nwk"
    threads: config["cpu_cores"]/2
    shell: "megatree-pruner -d {input[0]} -i {input[1]} > {output}"


rule edit_newick:
    input: "../data/fasta/alignment/{{family}}_{}_hmm.fasta".format(datatype), "../data/newick/{family}_constraint_temp.nwk"
    output:  "../data/newick/{family}_constraint.nwk"
    threads: config["cpu_cores"]/2
    script: "edit_constraint.py"


rule raxml:
    input:  "../data/fasta/alignment/{{family}}_{}_hmm.fasta".format(datatype), "../data/newick/{family}_constraint.nwk"
    output: "../data/raxml/{family}/{family}.raxml.bestTree"
    threads: config["cpu_cores"]
    script:
        "raxml.py"

rule create_matrix:
    input: "../data/raxml/{family}/{family}.raxml.bestTree"
    output: "../data/fasta/distance_matrix/{family}.txt"
    threads: 4
    script:
        "distance_matrix.py"


rule create_submatrices:
    input:
        "../data/fasta/distance_matrix/{family}.txt",
        ott_database_file
    output:
        "../data/fasta/submatrix/{family}.txt"
    threads:
        config["cpu_cores"]
    script:
        "create_submatrices.py"


rule get_representatives:
    input:
        "../data/fasta/distance_matrix/{family}.txt",
    output:
        "../data/fasta/representatives/rep.txt"
    threads:
        config["cpu_cores"]
    script:
        "get_representatives.py"


rule write_representatives:
    input:
        "../data/fasta/family/{family}.fasta",
        "../data/fasta/representatives/rep.txt"
    output:
        "../data/fasta/representatives/representatives.fasta"
    threads:
        config["cpu_cores"]
    script:
        "representatives_to_file.py"


rule insert_backbone:
    input:
        "../data/raxml/{family}/{family}.raxml.bestTree",
        "../data/raxml/representatives/representatives.fasta.raxml.bestTree"
    output:
        "../data/representatives/altered_backbone.nwk"
    threads:
        config["cpu_cores"]
    script:
        "insert_backbone.py"


rule all:
    input: dynamic("../data/fasta/distance_matrix/{family}.txt")
    threads: config["cpu_cores"]
    shell: "touch {input}"

